# Generated by Django 5.0.1 on 2024-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, default='users/default_user_img.png', null=True, upload_to=''),
        ),
    ]
