# Generated by Django 5.0.1 on 2024-01-11 16:47

import django.db.models.deletion
import magazin.utilities
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=magazin.utilities.set_id, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='products/default_product_img.png', upload_to='products/')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
