# Generated by Django 5.0.1 on 2024-02-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
